config/routes.rb
Rails.application.routes.draw do
  devise_for :mentors, skip: [:passwords], controllers: {
    registrations: "mentors/registrations",
    sessions: 'mentors/sessions'
  }

  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"
  get "/search_result" => "searches#search", as: "searches"
  resources :errors do
    resources :error_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :mentors, only: [:show, :edit, :update]
  resources :used_technologies, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :error
  belongs_to :mentor, optional: true
  validates_uniqueness_of :error_id, scope: :mentor_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    if mentor_signed_in?
      @error = Error.find(params[:error_id])
      @favorite = current_mentor.favorites.new
      @favorite.error_id = @error.id
      @favorite.save
    else
      flash[:alert] = "高評価する場合はログインしてください"
      redirect_to new_mentor_session_path
    end
  end

  def destroy
    @error = Error.find(params[:error_id])
    @favorite = current_mentor.favorites.find_by(error_id: @error.id)
    @favorite.destroy
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite_btn.html.erb
<% if error.favorited_by?(mentor) %>
  <%= link_to error_favorites_path(error.id), method: :delete, remote: true do %>
    <i class="fas fa-thumbs-up text-danger fa-3x"></i>  <span class="text-danger h5">高評価 <%= error.favorites.count %></span>
  <% end %>
<% else %>
  <%= link_to error_favorites_path(error.id), method: :post, remote: true do %>
    <i class="fas fa-thumbs-up text-secondary fa-3x"></i>   <span class="text-secondary h5">高評価 <%= error.favorites.count %></span>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn<%= @error.id %>").html("<%= j(render "favorite_btn", error: @error, mentor: current_mentor)%>");

app/views/favorites/destroy.js.erb
$(".favorite-btn<%= @error.id %>").html("<%= j(render "favorite_btn", error: @error, mentor: current_mentor)%>");