config/routes.rb
Rails.application.routes.draw do
  devise_for :mentors, skip: [:passwords], controllers: {
    registrations: "mentors/registrations",
    sessions: 'mentors/sessions'
  }

  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"
  get "/search_result" => "searches#search", as: "searches"
  resources :errors do
    resources :error_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :mentors, only: [:show, :edit, :update]
  resources :used_technologies, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @errors = Error.all
    @learning_phases = Error.learning_phases
  end

  def about
    @learning_phases = Error.learning_phases
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
about

app/views/homes/top.html.erb
<main>
  <div class="top">
    <div class="top-title">
      <h1>エラー掲示板</h1>
    </div>
      <%= link_to "新規投稿", new_error_path, class:"btn" %>
    <table class="top-table">
      <thead class="top-thead">
        <tr>
          <th class="thead-item">タイトル</th>
          <th class="thead-item">学習フェーズ</th>
          <th class="thead-item">技術項目</th>
          <th class="thead-item">URL</th>
          <th class="thead-item">担当者</th>
        </tr>
      </thead>
      <tbody class="top-tbody">
        <% @errors.each do |error| %>
          <tr>
            <td class="tbody-item">
              <%= link_to error_path(error) do %>
                <%= error.title %>
              <% end %>
            </td>
            <td class="tbody-item"><%= error.learning_phase_i18n %></td>
            <td class="tbody-item"><%= error.used_technology.name %></td>
            <td class="tbody-item"><a href=<%= error.url %> target="_blank" rel="noopener noreferrer"><%= error.url %></a></td>
            <td class="tbody-item"><%= error.mentor_name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</main>