config/routes.rb
Rails.application.routes.draw do
  devise_for :mentors, skip: [:passwords], controllers: {
    registrations: "mentors/registrations",
    sessions: 'mentors/sessions'
  }

  root to: 'homes#top'
  get "/about" => "homes#about", as: "about"
  get "/search_result" => "searches#search", as: "searches"
  resources :errors do
    resources :error_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :mentors, only: [:show, :edit, :update]
  resources :used_technologies, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @learning_phases = Error.learning_phases
    @word = params[:word]
    if params[:learning_phase].present?
      @learning_phase = params[:learning_phase]
      @errors = Error.search_for(@word, @learning_phase)
    else
      @errors = Error.search_for(@word, "all_phese")
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_form.html.erb
<%= form_with url: searches_path, method: :get, class:"form-inline", local: true do |f| %>
  <%= f.select :learning_phase, @learning_phases.keys.map {|k| [I18n.t("enums.error.learning_phase.#{k}"), k]}, { include_blank: "フェーズ全体検索" } %>
  <%= f.text_field :word, :placeholder => " 担当者名やエラーキーワード"  %>
  <%= f.submit "検索", class:"search-btn" %>
<% end %>

app/views/searches/search.html.erb
<main>
  <div class="search-results">
    <h4>検索結果  <%= @errors.count %>件</h4>
    <% if @errors.count == 0 %>
      <h3><strong>検索条件に一致するエラー情報は見つかりませんでした。</strong></h3>
    <% else %>
      <%= render "errors/searches_table", errors: @errors %>
    <% end %>
  </div>
</main>